resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
  demands: java
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Web/*

steps:
- task: Gradle@2
  displayName: 'gradlew build'
  inputs:
    gradleWrapperFile: Web/gradlew
    workingDirectory: Web
    publishJUnitResults: false

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: $(SERVICE_CONNECTION)
    azureContainerRegistry: $(ACR_SERVER)
    imageName: '$(ACR_SERVER)/pumrp/pumrp-web:$(Build.BuildNumber)'
    dockerFile: Web/Dockerfile
    useDefaultContext: false
    buildContext: '$(Build.SourcesDirectory)'
    addDefaultLabels: false
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: $(SERVICE_CONNECTION)
    azureContainerRegistry: $(ACR_SERVER)
    imageName: '$(ACR_SERVER)/pumrp/pumrp-web:$(Build.BuildNumber)'
    command: push