apiVersion: {{ .Values.apiversion.deployment }}
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-deployment
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
      tier: {{ .Values.labels.tier }}
      link: {{ .Values.labels.link }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
        tier: {{ .Values.labels.tier }}
        link: {{ .Values.labels.link }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: {{ .Values.service.portName }}
          containerPort: {{ .Values.service.internalPort }}
        env:
          - name: mongo_conn
            valueFrom:
              secretKeyRef:
                name: cosmosdb
                key: connection
          - name: mongo_database
            valueFrom:
              secretKeyRef:
                name: cosmosdb
                key: database
          - name: expose_port
            value: {{ .Values.service.internalPort | quote }}

