apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-svc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: "http-{{ .Values.image.name }}"
  selector:
    app: {{ .Values.image.name }}
    tier: {{ .Values.labels.tier }}
    link: {{ .Values.labels.link }}
